### ISSUE TITLE
How to use this gem for Rails4

### ISSUE THREAD

**Issue by datnt** [fnando/paypal-recurring#33]
Thank you fnando for great gem.

I was  using this on Rails3 and it worked just fine.

After install this gem for Rails4, and provide config/initializer/paypal.rb, we had this error:

/config/initializers/paypal.rb:3:in `<top (required)>': uninitialized constant Paypal (NameError)
    from /Users/danbrown/.rvm/gems/ruby-1.9.3-p448/gems/railties-4.1.0/lib/rails/engine.rb:648:in`block in load_config_initializer'
    from /Users/danbrown/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-4.1.0/lib/active_support/notifications.rb:161:in `instrument'
    from /Users/danbrown/.rvm/gems/ruby-1.9.3-p448/gems/railties-4.1.0/lib/rails/engine.rb:647:in`load_config_initializer'

**Comment by fnando** [comment]
That's strange. I'm using it with Rails 4.1. Can you replicate this error in a sample app?

## 

Nando Vieira

**Comment by Theminijohn** [comment]
Maybe late, but I had the same Problem:

You are using `Paypal` instead of `PayPal`
